- hosts: k8

  tasks:

    - name: Deploy application
      shell: |
        export KUBECONFIG=/home/ubuntu/.kube/config
        kubectl apply -f /home/ubuntu/deployment.yml

    - name: Deploy service
      shell: |
        export KUBECONFIG=/home/ubuntu/.kube/config
        kubectl apply -f /home/ubuntu/service.yml

    - name: Check pods
      shell: |
        export KUBECONFIG=/home/ubuntu/.kube/config
        kubectl get pods -A
      register: output

    - debug:
        var: output.stdout_lines
